twitch:
  client_id: ""
  client_secret: ""
  streamer: ""
  webhook:
    host: ""
    port: 42069
    ssl_port: 42070
    ssl_cert: "server.pem"
youtube:
  json: "secrets.json"
  arguments:
    description: ""
    categoryId: ""
    privacy: "private"
    tags:
      - "GTA RP"
      - "nopixel"
download:
  directory: ""