twitch:
  client_id: ":)"
  client_secret: ":)"
  streamer: ":)"
  webhook:
    host: ":)"
    port: ":)"
youtube:
  client_id: ":)"
  client_secret: ":)"
  redirect_uris: []
  auth_uri: "https://accounts.google.com/o/oauth2/auth"
  token_uri: "https://accounts.google.com/o/oauth2/auth"
download:
  directory: ":)"