twitch:
  client_id: ""
  client_secret: ""
  channel:
    name:
    youtube_param:
      description: ""
      categoryId: ""
      privacy: "private"
      tags:
        - "GTA RP"
        - "nopixel"
  webhook:
    host: ""
    port: 42069
    ssl_port: 42070
    ssl_cert: "server.pem"
youtube:
  json: "secrets.json"
download:
  directory: ""
