download:
  directory: /home/blazer/git/vodloader/videos
  keep: false
twitch:
  channels:
    Rlly:
      backlog: false
      chapters: titles
      quality: best
      timezone: America/Cambridge_Bay
      youtube_param:
        categoryId: '20'
        description: Follow %C at https://twitch.tv/%C to watch live!
        playlistId: PLRV-ewmAAe9rHVKkhr3hz3eSzME__G0si
        privacy: private
        tags:
        - GTA RP
        - nopixel
        title: '%C VOD %m/%d/%Y'
  client_id: cxlvasdfualsdm
  client_secret: dfalsdfusdofoiiulx
  webhook:
    host: mysupersecretdomain.com
    local: 192.168.1.2
    port: 42069
    ssl_cert: server.pem
    ssl_port: 42070
youtube:
  json: secrets.json
  upload: true
