twitch:
  client_id: "cxlvasdfualsdm"
  client_secret: "dfalsdfusdofoiiulx"
  channels:
    Ludwig:
      youtube_param:
        description: "A good looking chunk of word salad"
        categoryId: "20"
        privacy: "private"
        tags:
          - "GTA RP"
          - "nopixel"
  webhook:
    host: "mysupersecretdomain.com"
    port: 42069
    ssl_port: 42070
    ssl_cert: "server.pem"
youtube:
  json: "secrets.json"
download:
  directory: ""
